services:
  postgres:
    image: postgres
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: chinese-dictation-data
      POSTGRES_USER: vsung2608
      POSTGRES_PASSWORD: 260804
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - cd-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d myapp_db" ]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:latest
    container_name: redis-server
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - cd-network
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--appendonly", "yes" ]

networks:
  cd-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: