services:
  postgres:
    image: postgres
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: chinese-dictation-data
      POSTGRES_USER: vsung2608
      POSTGRES_PASSWORD: 260804
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d myapp_db" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: