server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: chinese-dictation
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB


application:
  security:
    jwt:
      expiration: 86400000
      secret-key: ${SECRET_KEY}
  email:
    brevo:
      api-key: ${BREVO_API_KEY}
      sender-email: ${BREVO_SENDER_EMAIL}
      sender-name: ${BREVO_SENDER_NAME}
  cloudinary:
    cloud-name: ${CLD_NAME}
    api-key: ${CLD_API_KEY}
    api-secret: ${CLD_API_SECRET}

logging:
  level:
    root: INFO  # Mức log chung
    org.springframework.web: DEBUG  # Log cho Spring Web (REST API)
    org.springframework.http.server: DEBUG  # Log request & response
    org.springframework.security: DEBUG  # Log bảo mật (nếu dùng Spring Security)
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

