server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: chinese-dictation
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
application:
  security:
    jwt:
      expiration: 86400000
      secret-key: ${SECRET_KEY}
  email:
    brevo:
      api-key: ${BREVO_API_KEY}
      sender-email: ${BREVO_SENDER_EMAIL}
      sender-name: ${BREVO_SENDER_NAME}

logging:
  level:
    root: INFO  # Mức log chung
    org.springframework.web: DEBUG  # Log cho Spring Web (REST API)
    org.springframework.http.server: DEBUG  # Log request & response
    org.springframework.security: DEBUG  # Log bảo mật (nếu dùng Spring Security)

