server:
  port: 8080
  servlet:
    context-path: api/v1

spring:
  application:
    name: chinese-dictation
  datasource:
    url: jdbc:postgresql://${DB-HOST}:${DB-PORT}/${DB-NAME}
    driver-class-name: org.postgresql.Driver
    username: ${USER-NAME}
    password: ${PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

application:
  security:
    jwt:
      expiration:
      secret-key: